### ISSUE TITLE
Prepare templating for AppD datasource

### ISSUE THREAD

**Issue by alyan2008** [grafana/appdynamics-grafana-datasource#10]
Hi

I have connected AppD datasource to Grafana  and created dashboards.

When I am trying to create template I get the error:

![image](https://user-images.githubusercontent.com/7196207/32381076-786793b4-c0ba-11e7-8755-6cbe081c9a64.png)

I can get the list of applications on the graph:

![image](https://user-images.githubusercontent.com/7196207/32381102-8ec7cd04-c0ba-11e7-85f9-461e884a02cd.png)

Grafana version - 4.6.0
AppD On Premise - 4.3.5.6

**Comment by dlopes7** [comment]
The latest version of the plugin, with templating, was not published to Grafana Labs yet, to use this feature you have to download the plugin directly from github.

We will publish it soon

**Comment by alyan2008** [comment]
I have just got the latest version from github but have the same problem. 
I cloned the repo and past content to "/var/lib/grafana/plugins/dlopes7-appdynamics-datasource". After that grafana-server was restarted.

![image](https://user-images.githubusercontent.com/7196207/32385647-807a2fdc-c0c7-11e7-9123-6f2c726563e3.png)

**Comment by dlopes7** [comment]
Alyan, I think that it is still using the incorrect version (I also forgot to add the version number update to the last commit so 1.0.2 doesn't say much), the error message is pretty clear saying that the method **metricFindQuery** does not exist, which really doesn't exists on the published version, only on the latest commit.

Could you please verify that you don't have 2 plugins on your plugins folder?

Execute
ls -l /var/lib/grafana/plugins/

If you have 2, delete the older one.
If you only have one, please check that you have the latest version by running:

grep getTemplateNames /var/lib/grafana/plugins/dlopes7-appdynamics-datasource/dist/appd_sdk.js

Thanks!

**Comment by dlopes7** [comment]
Also please make sure you either force a refresh of your browser (Ctrl + Shift + R) or use an incognito session to clear the cache before valdiating the templates

**Comment by alyan2008** [comment]
Hi

I deleted and uploaded plugin one more time but have the same problem:

![image](https://user-images.githubusercontent.com/7196207/32412944-961bb44e-c20e-11e7-9f7b-f5817d5acc9b.png)

**Comment by alyan2008** [comment]
Hi

Did you have a chance to check it?

**Comment by dlopes7** [comment]
Hello Alyan,

I'm a little stumped trying to recreate this locally, can you please update your grafana logs here?
Please make sure that you are running this in incognito and that there is only one grafana plugin installed. I've just cloned the plugin and tested it again here without any issues.

If you have a SAAS account, you can also email me an username and password for your controller at david.lopes@appdynamics.com and I can take a look at it.

**Comment by dlopes7** [comment]
Alyan,

I had another user report the same issue you did.
This happened because of Grafana caching, Grafana creates a huge .js file with all the plugins code, and your browser caches that file.

Using an anonymous window, or clearing your browser caches fixed the issue.

Please try that.
